name: Run flutter tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.10.0-2.0.dev"
      - run: flutter pub get
      - run: flutter test
