name: Run flutter tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 1.20.1
          channel: stable
      - run: flutter channel master
      - run: flutter upgrade --force
      - run: flutter pub get
      - run: flutter test
